import { execFileSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projects = [
  "ragforge",
  "sherpa-ai",
  "voiceclone-pro",
  "multimind",
  "copiloc",
  "evalbench",
  "mcpgate",
  "compudops",
  "promptops",
  "mnemoai",
  "openlatam",
  "cryptolat",
  "sendylat",
  "compraya",
  "pymebank",
  "scorelat",
  "treasuryx",
  "factorlat",
  "escrowchain",
  "payhub",
  "telemedlat",
  "cronoshr",
  "triajeai",
  "medreminder",
  "calmamente",
  "fitcoach",
  "nutriplan",
  "genomalab",
  "biowear",
  "saludmarket",
  "carbontrack",
  "carbonmarket",
  "airesensor",
  "solarmesh",
  "reforestapp",
  "agrisust",
  "recicalop",
  "climamodel",
  "evhub",
  "esgreport",
  "aulalat",
  "pathfinderai",
  "cursoslive",
  "testprep",
  "codeacad",
  "idiomaslatam",
  "kidsacad",
  "certverify",
  "skillboard",
  "teachershub",
  "flagship",
  "observalat",
  "deployhaus",
  "secretsvault",
  "apimesh",
  "cichain",
  "snapdb",
  "edgefn",
  "chaostest",
  "costmonitor",
  "daolatam",
  "nftarte",
  "tokenlaunch",
  "bridgechain",
  "realestatechain",
  "identityid",
  "socialfi",
  "privyvote",
  "supplychain",
  "charitychain",
  "citysense",
  "parkingiq",
  "watergrid",
  "wastesmart",
  "seguridadcom",
  "flotatrack",
  "almacenbot",
  "agridrone",
  "saludrural",
  "edificioiq",
  "creadorpro",
  "podcastlat",
  "newsletterx",
  "shortlat",
  "liveauction",
  "fanclub",
  "merchprint",
  "musicsplit",
  "aistudio",
  "rightsmanage"
];
let okCount = 0, fail = [];
for (const slug of projects) {
  try {
    execFileSync('node', ['scripts/validate.mjs'], { cwd: path.join(__dirname, slug), stdio: 'inherit' });
    okCount++;
  } catch (e) { fail.push(slug); }
}
console.log(`\nValidated ${okCount}/${projects.length} projects.`);
if (fail.length) { console.error('Failed:', fail.join(', ')); process.exit(1); }
